---
title: "GWAS to Identify Antimicrobial Susceptibility in *Neisseria Gonorrhoeae*"
subtitle: "Background and Replication of Paper"
page-layout: full
---

This project discusses the background behind the methodologies of the paper "Adaptation to the cervical environment is associated with increased antibiotic susceptibility in *Neisseria gonorrhoeae*" by Ma, K.C., Mortimer, T.D., Hicks, A.L. et al. We are focusing on methods of using GWAS (genome wide association studies) to identify antimicrobial susceptibility in the bacteria that causes the gonorrhea STI: *Neisseria gonorrhoeae*. Some topics we will cover include explaining population structure of the bacteria, what unitigs are, and how this research uses linear mixed models to predict MIC (minimum inhibitory concentration) of the antibiotic called azithromycin as it is used against the bacteria. 

There is much more to learn about the research done by the authors of this paper, and we will only cover a small portion of it. For example, they focus on three different drugs that are commonly used to treat gonorrhea: azithromycin, ciprofloxacin, and ceftriaxone. Additionally, the researchers focus on environmental factors such as where the bacteria is located in the human host as factors impacting the evolutionary traits of Neisseria gonorrhoeae.

To explore the topics in the part of the paper we are focusing on, visit the different sections of our website. If there is a term you don’t quite understand, check out the vocabulary section.

### Acknowledgements

This repo and GitHub Action was based on the tutorial by Openscapes [quarto-website-tutorial](https://github.com/Openscapes/quarto-website-tutorial) by Julia Lowndes and Stefanie Butland.