---
title: Bibliography
---

CDC. “About Antimicrobial Resistance.” Antimicrobial Resistance, December 11, 2024.
https://www.cdc.gov/antimicrobial-resistance/about/index.html.

Ma, K. C., Mortimer, T. D., Hicks, A. L., Wheeler, N. E., Sánchez-Busó, L., Golparian, D.,
Taiaroa, G.,Rubin, D. H. F., Wang, Y., Williamson, D. A., Unemo, M., Harris, S. R., & Grad, Y. H. (2020). Adaptation to the cervical environment is associated with increased antibiotic susceptibility in Neisseria gonorrhoeae. Nature Communications, 11(1), 4126. https://doi.org/10.1038/s41467-020-17980-1

Oliveira, J., & Reygaert, W. C. (2025). Gram-Negative Bacteria. In StatPearls. StatPearls
Publishing. http://www.ncbi.nlm.nih.gov/books/NBK538213/

Shaskolskiy, B., Kravtsov, D., Kandinov, I., Gorshkova, S., Kubanov, A., Solomka, V., Deryabin, D., Dementieva, E., & Gryadunov, D. (2022). Comparative Whole-Genome Analysis of Neisseria gonorrhoeae Isolates Revealed Changes in the Gonococcal Genetic Island and Specific Genes as a Link to Antimicrobial Resistance. Frontiers in Cellular and Infection Microbiology, 12. https://doi.org/10.3389/fcimb.2022.831336

Unemo, M., & Shafer, W. M. (2011). Antibiotic resistance in Neisseria gonorrhoeae: Origin, evolution,
and lessons learned for the future. Annals of the New York Academy of Sciences, 1230, E19–E28.
https://doi.org/10.1111/j.1749-6632.2011.06215.x
